#!/bin/sh

function build_tarballs () {
    # variables needed by the generate-tarballs
    export RUN_FILE="$ROOT/$RUNFILENAME"
    export extension=$TARTYPE
    export major=$VMAJOR
    export arch=$ARCH

    rm -rf temp
    # generate the tarballs
    if [ -z $DONT_BUILD_TARBALLS ]; then
        if [ "$ARCH" == "aarch64" ]; then 
              ./nvidia-generate-tarballs-${ARCH}.sh
        elif [ "$ARCH" == "pp64le" ]; then 
            ./nvidia-generate-tarballs-${ARCH}.sh
        else
            ./nvidia-generate-tarballs.sh
        fi
    fi
}
