#!/bin/sh

function build_dkms () {
    echo "actual version detected: $ACTUAL_VERSION"
    # bring the tarball from before into this directory
    rsync -av ../yum-packaging-nvidia-driver/nvidia-kmod-${ACTUAL_VERSION}-${ARCH}.tar.xz $PWD/
    
    # set up build
    mkdir -p BUILD BUILDROOT RPMS SRPMS SOURCES SPECS
    cp dkms-nvidia.conf SOURCES/
    # convert tarball to use VERSION instead of ACTUAL_VERSION
    mv nvidia-kmod-${ACTUAL_VERSION}-${ARCH}.tar.xz SOURCES/nvidia-kmod-${VERSION}-${ARCH}.tar.xz
    cp dkms-nvidia.spec SPECS/  
    rpmbuild \
        --define "%_topdir $(pwd)" \
        --define "debug_package %{nil}" \
        --define "version $VERSION" \
        --define "driver_branch latest-dkms" \
        --define "is_dkms 1" \
        --define "is_latest 1" \
        --define "epoch 3" \
        --target "${arch}" \
        -v -bb SPECS/dkms-nvidia.spec
    [ -n $VERBOSE ] && echo ">>> COPYING DKMS TO OUTPUT..."
    find -name "*.rpm" -exec cp -v {} $OUTPUT/ \;
}
